DATA:
  data_name: pascal
  split: 0                      # [0, 1, 2, 3] refer to PASCAL-5^i, [10, 11] refer to PASCAL-10^i
  train_list: lists/pascal/train.txt
  data_root: ./data/pascal
  val_list: lists/pascal/val.txt
  num_classes_tr: 16  # Counting background for training
  num_classes_val: 5
  use_split_coco: False
  workers: 0
  image_size: 473
  patch_size: 14
  mean: [0.485, 0.456, 0.406]
  std: [0.229, 0.224, 0.225]
  padding_label: 255
  pin_memory: True

MODEL:
  arch: resnet #[Dino2, Diet, ViT, resnet]
  pretrained: True
  bins: [1, 2, 3, 6]
  dropout: 0.1
  m_scale: False
  layers: 50
  bottleneck_dim: 512
  feature_res: [60, 60]

TRAIN:
  ckpt_path: checkpoints/
  batch_size: 8
  epochs: 100
  log_freq : 50
  save_models: True
  lr: 0.0025
  cls_lr: 0.1
  scale_lr: 2.0
  mixup: False
  lr_stepsize: 30
  momentum: 0.9
  gamma: 0.1
  nesterov: True
  weight_decay: 0.0001
  main_optim: SGD
  scheduler: cosine
  milestones: [40, 70]


EVALUATION:
  episodic_val: False
  debug: False
  ckpt_path: model_ckpt/
  load_model_id: 1
  ckpt_used: model
  test_num: -1                  # i.e., use all the test data
  shot: 1
  batch_size_val: 100           # Trade-off between speed and memory usage, no effect on the results
  n_runs: 5
  support_only_one_novel: True  # It might help the model unfairly if a single support image has information about multiple novel classes, so set to True
  use_training_images_for_supports: False
  generate_new_support_set_for_each_task: False
  shuffle_test_data: True
  manual_seed: 42
  gpus: [0]


Segmenthead:
  seghead: "None"  #["None", "UPerNet"]
  train_seg: False

CLASSIFIER:
  weights: [100, 1, 1, 100]
  adapt_iter: 100
  cls_lr: 0.00125
  pi_estimation_strategy: self  # ['uniform', 'self', 'imglvl', 'upperbound']
  pi_update_at: [10]
  fine_tune_base_classifier: True
  clsfer: DIaM #['Linear', 'DIaM']

EXPERIMENT:
  exp_name: pspnet_resnet50 #[pspnet_resnet50, dino2_upernet, dino2_None]  for model ckpt load


# dino, image_size: 448, arch: dino 
# psp , image_size: 417, arch: resnet


LABELPROPAGATION:
  lp_type: 0
  k: 5
  w_type: 'poly'
  gamma: 1.0
